# 简单入口：让 ComfyUI 自动发现节点类映射
from .duck_encode_node import NODE_CLASS_MAPPINGS as STEG_NODES, NODE_DISPLAY_NAME_MAPPINGS as STEG_DISPLAY
from .duck_decode_node import NODE_CLASS_MAPPINGS as DECODE_NODES, NODE_DISPLAY_NAME_MAPPINGS as DECODE_DISPLAY

NODE_CLASS_MAPPINGS = {**STEG_NODES, **DECODE_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**STEG_DISPLAY, **DECODE_DISPLAY}

